---
title: "Things You Can Do With R"
author: "Alexander Poon"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
    ioslides_presentation:
        incremental: true
        widescreen: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## R

* A programming language
* Free and open source
* Lots of resources on the web for learning and support

## Why use R?

* Streamline your workflow!
* R has packages for every stage of the data science process:
    + Reading in data
    + Manipulating/cleaning data
    + Modeling
    + **Visualizations**
    + **Creating documents, presentations, web applications**

## Documents

* Create Word, PDF, HTML documents with R Markdown and the `knitr` package
* Embed your R code within a document so that your analysis is reproducible
* Mass produce documents with a loop

## Interactive Web Applications

* Create interactive web applications with the `shiny` package.

## Presentations

* Create web based (HTML) presentations (like this one!)
* Mass produce presentations with a loop
* Add interactivity with `shiny` elements

## Learning R

* Internal Training:
    + Intro to R (Bob Muenchen, UT)
    + R quickstart (Alex)
    + Creating documents with R Markdown and `knitr` (?)
    + Interactive web applications in `shiny` (?)

* Resources for self-paced learning:
    + The online book [R for data science](http://r4ds.had.co.nz/), with accompanying [slides](https://github.com/rstudio/Intro/tree/master/slides)
    + `swirl` Package
    + [Datacamp](https://www.datacamp.com/)
    + [Webinars](https://www.rstudio.com/resources/webinars/) by RStudio

* Also recommended: Version control with Git(Hub)

## Support/Troubleshooting

* Look at the documentation
    + Type `?[name of function]` into the console to pull up the documentation
* Look for examples on the web
    + Google "R [name of package and/or function]" or "R [what you want to do]"
    + There are often more elaborate examples and vignettes on the web than in the documentation
* Stack Overflow + Google Groups
    + Forums with lots of answered questions, or ask your own
